[package]
name = "chainsawman-api"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
lazy_static = "1.4.0"
regex = "1.7.0"
reqwest = "0.11.12"
scraper = "0.13.0"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

